FROM ubuntu:22.04

RUN --mount=type=cache,target=/var/lib/apt/lists \
  --mount=type=cache,target=/var/cache,sharing=locked \
  apt-get update \
  && apt-get install --yes build-essential git cmake python3 \
  zlib1g-dev libssl-dev libcurlpp-dev

WORKDIR /opt/

RUN git clone --recurse-submodules https://github.com/aws/aws-sdk-cpp.git \
    && cd aws-sdk-cpp \
	&& git checkout 1.11.205

WORKDIR /opt/aws-sdk-cpp/build


RUN --mount=type=cache,target=/opt/aws-sdk-cpp/build \
  cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchains/gcc-c++20.cmake -DBUILD_ONLY="s3" \
  && cmake --build . \
  && cmake --install .

WORKDIR /app

COPY . .

WORKDIR /app/build

RUN --mount=type=cache,target=/app/build \
  cmake .. -DWITH_AWS_SDK=ON \
  && make \
  && cp extract_area extract_profile /usr/bin \
  && cp liblaszip.so /usr/lib

RUN extract_profile --help
